#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [15]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)

a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [19]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 1)

b1, b2, b3, b4, b5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [23]:
if a5.ndim == 1:
    print('Можно')
else: 
    print('Нельзя')

Нельзя


#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [44]:
c = np.random.randn(3, 4)
c

array([[ 1.48044159,  0.27314956, -0.21069669, -0.07447857],
       [-0.7239986 ,  1.14090657, -0.24019722, -1.25673927],
       [ 0.29758353,  1.27426325, -0.71447556,  0.68059403]])

In [45]:
c1 = c.flatten()
c1

array([ 1.48044159,  0.27314956, -0.21069669, -0.07447857, -0.7239986 ,
        1.14090657, -0.24019722, -1.25673927,  0.29758353,  1.27426325,
       -0.71447556,  0.68059403])

In [46]:
c.size == c1.size

True

#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [3]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [4]:
b = np.arange(20, 0, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив a - одномерный, массив b - двумерный. 
Обращение к элементам массива a осуществляется по индексу элемента. 
Обращение к элементам массива b - по индексам строки и столбца

In [9]:
print(a[5])
print(b[0, 5])
print("*"*60)
print(b[5])   #Вернёт ошибку

10
10
************************************************************


IndexError: index 5 is out of bounds for axis 0 with size 1

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [19]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
v.size


[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [46]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [49]:
B = np.dot(A, At)
print(B)
print(f"Размер матрицы В - {B.size}")

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы В - 16


In [50]:
if np.linalg.det(B) == 0:
    print("Нельзя вычислить обратную матрицу, так как определитель равен 0.")
else: 
    print("Можно вычислить обратную матрицу, так как определитель отличен от 0.")

Нельзя вычислить обратную матрицу, так как определитель равен 0.


#### 10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [42]:
np.random.seed(42)    #Этот метод устарел и не рекомендуется в новой документации

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [61]:
c = np.random.randint(0, 16, (16))
c

array([ 1,  3,  8, 11, 13,  1,  9,  8,  9,  4,  1,  3, 11, 14, 11,  6])

#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [62]:
C = c.reshape(4, 4)
C

array([[ 1,  3,  8, 11],
       [13,  1,  9,  8],
       [ 9,  4,  1,  3],
       [11, 14, 11,  6]])

In [63]:
D = np.dot(C, 10) + B
D

array([[ 15,  44, 103, 142],
       [144,  60, 176, 202],
       [113, 126, 159, 242],
       [142, 262, 322, 362]])

In [76]:
print(f"Определитель матрицы D = {np.linalg.det(D)}")
print(f"Ранг матрицы D = {np.linalg.matrix_rank(D)}\n")
D_inv = np.linalg.inv(D)
D_inv

Определитель матрицы D = -131179000.0000003
Ранг матрицы D = 4



array([[-0.01288362,  0.0059633 ,  0.0049479 , -0.0015815 ],
       [-0.00987109, -0.00748153,  0.00457909,  0.00498571],
       [ 0.00448502,  0.00845151, -0.0201857 ,  0.00701896],
       [ 0.00820863, -0.00444202,  0.0127002 , -0.00646902]])

#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [80]:
D_inv = np.where(D_inv > 0, 1, 0)
D_inv

array([[0, 1, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 1, 0]])

In [86]:
print(f"{B}\n")
print(f"{C}\n")
E = np.where(D_inv == 1, B, C)
print(E)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

[[ 1  3  8 11]
 [13  1  9  8]
 [ 9  4  1  3]
 [11 14 11  6]]

[[  1  14  23  11]
 [ 13   1  86 122]
 [ 23  86   1 212]
 [ 32  14 212   6]]
